FROM golang:1.23.0-alpine as builder
WORKDIR /go/src/app
COPY . .
RUN go build 

FROM alpine:3.18
COPY --from=builder /go/src/app/TaipeiCityDashboardBE /app/
RUN apk --no-cache add postgresql-client
WORKDIR /app
EXPOSE 8081
ENTRYPOINT ["./TaipeiCityDashboardBE"]